#############################################################################
# Generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#  Mar 26, 2020 03:46:15 PM PDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #4f7975 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #4f7975 
    wm focusmodel $top passive
    wm geometry $top 508x398+388+140
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra44 \
        -relief groove -background #c6c9af -height 85 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 355 
    vTcl:DefineAlias "$top.fra44" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    frame $site_3_0.fra50 \
        -relief groove -background #ffffff -height 67 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 461 
    vTcl:DefineAlias "$site_3_0.fra50" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra50
    frame $site_4_0.fra136 \
        -borderwidth 1 -relief groove -background #ffffff -height 54 \
        -width 448 
    vTcl:DefineAlias "$site_4_0.fra136" "Frame8" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra136
    entry $site_5_0.ent138 \
        -background white -borderwidth 0 -disabledforeground #a3a3a3 \
        -font {-family {Courier New} -size 20 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify right -selectbackground #c4c4c4 \
        -selectforeground black -textvariable toDisplay -width 434 
    vTcl:DefineAlias "$site_5_0.ent138" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.ent138 \
        -in $site_5_0 -x 0 -relx 0.013 -y 0 -rely 0.13 -width 434 -relwidth 0 \
        -height 40 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.fra136 \
        -in $site_4_0 -x 0 -relx 0.013 -y 0 -rely 0.104 -width 0 \
        -relwidth 0.972 -height 0 -relheight 0.806 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra50 \
        -in $site_3_0 -x 0 -relx 0.017 -y 0 -rely 0.114 -width 0 \
        -relwidth 0.964 -height 0 -relheight 0.761 -anchor nw \
        -bordermode ignore 
    frame $top.fra45 \
        -relief groove -background #c6c9af -height 292 -width 425 
    vTcl:DefineAlias "$top.fra45" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    frame $site_3_0.fra125 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 285 -width 235 
    vTcl:DefineAlias "$site_3_0.fra125" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra125
    frame $site_4_0.fra130 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 215 -width 215 
    vTcl:DefineAlias "$site_4_0.fra130" "Frame6" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra130
    frame $site_5_0.fra131 \
        -relief groove -background $vTcl(actual_gui_bg) -height 220 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 217 
    vTcl:DefineAlias "$site_5_0.fra131" "Frame6_23" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_0.fra131
    button $site_6_0.but98 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(1) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 1 
    vTcl:DefineAlias "$site_6_0.but98" "Button1_16" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but99 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(2) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 2 
    vTcl:DefineAlias "$site_6_0.but99" "Button1_17" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but100 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(3) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 3 
    vTcl:DefineAlias "$site_6_0.but100" "Button1_18" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but101 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(4) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 4 
    vTcl:DefineAlias "$site_6_0.but101" "Button1_19" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but102 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(5) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 5 
    vTcl:DefineAlias "$site_6_0.but102" "Button1_20" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but103 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(6) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 6 
    vTcl:DefineAlias "$site_6_0.but103" "Button1_20" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but104 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(7) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 7 
    vTcl:DefineAlias "$site_6_0.but104" "Button1_21" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but106 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(8) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 8 
    vTcl:DefineAlias "$site_6_0.but106" "Button1_21" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but107 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(9) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 9 
    vTcl:DefineAlias "$site_6_0.but107" "Button1_21" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but109 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -command numPressed(0) \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text 0 
    vTcl:DefineAlias "$site_6_0.but109" "Button1_22" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but110 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {( )} 
    vTcl:DefineAlias "$site_6_0.but110" "Button1_23" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but111 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text ^ 
    vTcl:DefineAlias "$site_6_0.but111" "Button1_23" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.but98 \
        -in $site_6_0 -x 0 -y 0 -width 57 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_6_0.but99 \
        -in $site_6_0 -x 0 -relx 0.327 -y 0 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but100 \
        -in $site_6_0 -x 0 -relx 0.643 -y 0 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but101 \
        -in $site_6_0 -x 0 -y 0 -rely 0.245 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but102 \
        -in $site_6_0 -x 0 -relx 0.325 -y 0 -rely 0.25 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but103 \
        -in $site_6_0 -x 0 -relx 0.645 -y 0 -rely 0.25 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but104 \
        -in $site_6_0 -x 0 -y 0 -rely 0.5 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but106 \
        -in $site_6_0 -x 0 -relx 0.322 -y 0 -rely 0.494 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but107 \
        -in $site_6_0 -x 0 -relx 0.643 -y 0 -rely 0.494 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but109 \
        -in $site_6_0 -x 0 -relx 0.322 -y 0 -rely 0.739 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but110 \
        -in $site_6_0 -x 0 -y 0 -rely 0.739 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but111 \
        -in $site_6_0 -x 0 -relx 0.643 -y 0 -rely 0.739 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.fra131 \
        -in $site_5_0 -x 0 -relx 0.082 -y 0 -rely 0.071 -width 0 \
        -relwidth 0.893 -height 0 -relheight 0.913 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra130 \
        -in $site_4_0 -x 0 -relx 0.043 -y 0 -rely 0.042 -width 0 \
        -relwidth 0.915 -height 0 -relheight 0.907 -anchor nw \
        -bordermode ignore 
    frame $site_3_0.fra133 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 235 -width 165 
    vTcl:DefineAlias "$site_3_0.fra133" "Frame5" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra133
    frame $site_4_0.fra134 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 215 -width 145 
    vTcl:DefineAlias "$site_4_0.fra134" "Frame7" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.fra134
    frame $site_5_0.fra135 \
        -relief groove -background $vTcl(actual_gui_bg) -height 195 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_5_0.fra135" "Frame7_24" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_5_0.fra135
    button $site_6_0.but81 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text + 
    vTcl:DefineAlias "$site_6_0.but81" "Button1_13" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but88 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text - 
    vTcl:DefineAlias "$site_6_0.but88" "Button1_14" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but89 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text x 
    vTcl:DefineAlias "$site_6_0.but89" "Button1_15" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but90 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text / 
    vTcl:DefineAlias "$site_6_0.but90" "Button1_15" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but91 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text % 
    vTcl:DefineAlias "$site_6_0.but91" "Button1_15" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but92 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text +- 
    vTcl:DefineAlias "$site_6_0.but92" "Button1_16" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but93 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text C 
    vTcl:DefineAlias "$site_6_0.but93" "Button1_16" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but94 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text = 
    vTcl:DefineAlias "$site_6_0.but94" "Button1_16" vTcl:WidgetProc "Toplevel1" 1
    button $site_6_0.but128 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 24 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text x 
    vTcl:DefineAlias "$site_6_0.but128" "Button1_14" vTcl:WidgetProc "Toplevel1" 1
    place $site_6_0.but81 \
        -in $site_6_0 -x 0 -y 0 -width 57 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $site_6_0.but88 \
        -in $site_6_0 -x 0 -relx 0.484 -y 0 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but89 \
        -in $site_6_0 -x 0 -relx -1.748 -y 0 -rely 0.116 -width 57 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but90 \
        -in $site_6_0 -x 0 -relx 0.484 -y 0 -rely 0.255 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but91 \
        -in $site_6_0 -x 0 -y 0 -rely 0.51 -width 57 -height 44 -anchor nw \
        -bordermode ignore 
    place $site_6_0.but92 \
        -in $site_6_0 -x 0 -relx 0.484 -y 0 -rely 0.51 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but93 \
        -in $site_6_0 -x 0 -y 0 -rely 0.765 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but94 \
        -in $site_6_0 -x 0 -relx 0.484 -y 0 -rely 0.765 -width 57 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_6_0.but128 \
        -in $site_6_0 -x 0 -y 0 -rely 0.256 -width 57 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.fra135 \
        -in $site_5_0 -x 0 -relx 0.122 -y 0 -rely 0.066 -width 0 \
        -relwidth 0.86 -height 0 -relheight 0.905 -anchor nw \
        -bordermode ignore 
    place $site_4_0.fra134 \
        -in $site_4_0 -x 0 -relx 0.061 -y 0 -rely 0.043 -width 0 \
        -relwidth 0.879 -height 0 -relheight 0.915 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra125 \
        -in $site_3_0 -x 0 -relx 0.024 -y 0 -rely 0.04 -width 0 \
        -relwidth 0.553 -height 0 -relheight 0.94 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra133 \
        -in $site_3_0 -x 0 -relx 0.588 -y 0 -rely 0.04 -width 0 \
        -relwidth 0.388 -height 0 -relheight 0.933 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra44 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.026 -width 0 -relwidth 0.942 \
        -height 0 -relheight 0.221 -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 0 -relx 0.027 -y 0 -rely 0.261 -width 0 -relwidth 0.942 \
        -height 0 -relheight 0.712 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

