#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Mar 26, 2020 03:48:14 PM PDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unknown_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    unknown_support.set_Tk_var()
    top = Toplevel1 (root)
    unknown_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    unknown_support.set_Tk_var()
    top = Toplevel1 (w)
    unknown_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("508x398+388+140")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(0, 0)
        top.title("New Toplevel")
        top.configure(background="#4f7975")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#4f7975")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.028, rely=0.025, relheight=0.221
                , relwidth=0.941)
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#c6c9af")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.017, rely=0.114, relheight=0.761
                , relwidth=0.964)
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#ffffff")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Frame8 = tk.Frame(self.Frame2)
        self.Frame8.place(relx=0.013, rely=0.104, relheight=0.806
                , relwidth=0.972)
        self.Frame8.configure(relief='groove')
        self.Frame8.configure(borderwidth="1")
        self.Frame8.configure(relief="groove")
        self.Frame8.configure(background="#ffffff")

        self.Entry1 = tk.Entry(self.Frame8, validate="key")
        self.Entry1.place(relx=0.013, rely=0.13,height=40, relwidth=0.969)
        self.Entry1.configure(background="white")
        self.Entry1.configure(borderwidth="0")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="-family {Courier New} -size 26 -weight bold")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(justify='right')
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(textvariable=unknown_support.toDisplay)
        self.Entry1['validatecommand'] = (self.Entry1.register(unknown_support.validateInput),'%P','%d')
        # self.Entry1.configure(state=tk.DISABLED)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.028, rely=0.261, relheight=0.711
                , relwidth=0.941)
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#c6c9af")
        self.Frame3.configure(cursor="fleur")

        self.Frame4 = tk.Frame(self.Frame3)
        self.Frame4.place(relx=0.023, rely=0.039, relheight=0.94, relwidth=0.554)

        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#d9d9d9")

        self.Frame6 = tk.Frame(self.Frame4)
        self.Frame6.place(relx=0.042, rely=0.041, relheight=0.906
                , relwidth=0.917)
        self.Frame6.configure(relief='groove')
        self.Frame6.configure(borderwidth="2")
        self.Frame6.configure(relief="groove")
        self.Frame6.configure(background="#d9d9d9")

        self.Frame6_23 = tk.Frame(self.Frame6)
        self.Frame6_23.place(relx=0.082, rely=0.071, relheight=0.913
                , relwidth=0.893)
        self.Frame6_23.configure(relief="groove")
        self.Frame6_23.configure(background="#d9d9d9")
        self.Frame6_23.configure(highlightbackground="#d9d9d9")
        self.Frame6_23.configure(highlightcolor="black")

        self.Button1 = tk.Button(self.Frame6_23)
        self.Button1.place(relx=0.0, rely=0.0, height=44, width=57)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=lambda: unknown_support.numPressed(1))
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''1''')

        self.Button2 = tk.Button(self.Frame6_23)
        self.Button2.place(relx=0.327, rely=0.0, height=44, width=57)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=lambda: unknown_support.numPressed(2))
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''2''')

        self.Button3 = tk.Button(self.Frame6_23)
        self.Button3.place(relx=0.645, rely=0.0, height=44, width=57)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=lambda: unknown_support.numPressed(3))
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''3''')

        self.Button4 = tk.Button(self.Frame6_23)
        self.Button4.place(relx=0.0, rely=0.245, height=44, width=57)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(command=lambda: unknown_support.numPressed(4))
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''4''')

        self.Button5 = tk.Button(self.Frame6_23)
        self.Button5.place(relx=0.327, rely=0.25, height=44, width=57)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(command=lambda: unknown_support.numPressed(5))
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''5''')

        self.Button6 = tk.Button(self.Frame6_23)
        self.Button6.place(relx=0.645, rely=0.25, height=44, width=57)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(command=lambda: unknown_support.numPressed(6))
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''6''')

        self.Button7 = tk.Button(self.Frame6_23)
        self.Button7.place(relx=0.0, rely=0.5, height=44, width=57)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(command=lambda: unknown_support.numPressed(7))
        self.Button7.configure(cursor="fleur")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''7''')

        self.Button8 = tk.Button(self.Frame6_23)
        self.Button8.place(relx=0.323, rely=0.495, height=44, width=57)
        self.Button8.configure(activebackground="#ececec")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(command=lambda: unknown_support.numPressed(8))
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''8''')

        self.Button9 = tk.Button(self.Frame6_23)
        self.Button9.place(relx=0.645, rely=0.495, height=44, width=57)
        self.Button9.configure(activebackground="#ececec")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(command=lambda: unknown_support.numPressed(9))
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(text='''9''')

        self.Button0 = tk.Button(self.Frame6_23)
        self.Button0.place(relx=0.323, rely=0.741, height=44, width=57)
        self.Button0.configure(activebackground="#ececec")
        self.Button0.configure(activeforeground="#000000")
        self.Button0.configure(background="#d9d9d9")
        self.Button0.configure(command=lambda: unknown_support.numPressed(0))
        self.Button0.configure(disabledforeground="#a3a3a3")
        self.Button0.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button0.configure(foreground="#000000")
        self.Button0.configure(highlightbackground="#d9d9d9")
        self.Button0.configure(highlightcolor="black")
        self.Button0.configure(pady="0")
        self.Button0.configure(text='''0''')

        self.Button10 = tk.Button(self.Frame6_23)
        self.Button10.place(relx=0.0, rely=0.741, height=44, width=57)
        self.Button10.configure(activebackground="#ececec")
        self.Button10.configure(activeforeground="#000000")
        self.Button10.configure(background="#d9d9d9")
        self.Button10.configure(disabledforeground="#a3a3a3")
        self.Button10.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button10.configure(foreground="#000000")
        self.Button10.configure(highlightbackground="#d9d9d9")
        self.Button10.configure(highlightcolor="black")
        self.Button10.configure(pady="0")
        self.Button10.configure(text='''( )''')
        self.Button10.configure(command=lambda: unknown_support.numPressed("()"))


        self.Button11 = tk.Button(self.Frame6_23)
        self.Button11.place(relx=0.645, rely=0.741, height=44, width=57)
        self.Button11.configure(activebackground="#ececec")
        self.Button11.configure(activeforeground="#000000")
        self.Button11.configure(background="#d9d9d9")
        self.Button11.configure(disabledforeground="#a3a3a3")
        self.Button11.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button11.configure(foreground="#000000")
        self.Button11.configure(highlightbackground="#d9d9d9")
        self.Button11.configure(highlightcolor="black")
        self.Button11.configure(pady="0")
        self.Button11.configure(text='''^''')
        self.Button11.configure(command=lambda: unknown_support.numPressed("^()"))


        self.Frame5 = tk.Frame(self.Frame3)
        self.Frame5.place(relx=0.588, rely=0.039, relheight=0.933
                , relwidth=0.389)
        self.Frame5.configure(relief='groove')
        self.Frame5.configure(borderwidth="2")
        self.Frame5.configure(relief="groove")
        self.Frame5.configure(background="#d9d9d9")
        self.Frame5.configure(cursor="fleur")

        self.Frame7 = tk.Frame(self.Frame5)
        self.Frame7.place(relx=0.059, rely=0.042, relheight=0.917
                , relwidth=0.882)
        self.Frame7.configure(relief='groove')
        self.Frame7.configure(borderwidth="2")
        self.Frame7.configure(relief="groove")
        self.Frame7.configure(background="#d9d9d9")

        self.Frame7_24 = tk.Frame(self.Frame7)
        self.Frame7_24.place(relx=0.122, rely=0.066, relheight=0.905
                , relwidth=0.86)
        self.Frame7_24.configure(relief="groove")
        self.Frame7_24.configure(background="#d9d9d9")
        self.Frame7_24.configure(highlightbackground="#d9d9d9")
        self.Frame7_24.configure(highlightcolor="black")

        self.Button12 = tk.Button(self.Frame7_24)
        self.Button12.place(relx=0.0, rely=0.0, height=44, width=57)
        self.Button12.configure(activebackground="#ececec")
        self.Button12.configure(activeforeground="#000000")
        self.Button12.configure(background="#d9d9d9")
        self.Button12.configure(disabledforeground="#a3a3a3")
        self.Button12.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button12.configure(foreground="#000000")
        self.Button12.configure(highlightbackground="#d9d9d9")
        self.Button12.configure(highlightcolor="black")
        self.Button12.configure(pady="0")
        self.Button12.configure(text='''+''')
        self.Button12.configure(command=lambda: unknown_support.numPressed("+"))


        self.Button13 = tk.Button(self.Frame7_24)
        self.Button13.place(relx=0.482, rely=0.0, height=44, width=57)
        self.Button13.configure(activebackground="#ececec")
        self.Button13.configure(activeforeground="#000000")
        self.Button13.configure(background="#d9d9d9")
        self.Button13.configure(disabledforeground="#a3a3a3")
        self.Button13.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button13.configure(foreground="#000000")
        self.Button13.configure(highlightbackground="#d9d9d9")
        self.Button13.configure(highlightcolor="black")
        self.Button13.configure(pady="0")
        self.Button13.configure(text='''-''')
        self.Button13.configure(command=lambda: unknown_support.numPressed("-"))


        self.Button14 = tk.Button(self.Frame7_24)
        self.Button14.place(relx=-1.745, rely=0.114, height=44, width=57)
        self.Button14.configure(activebackground="#ececec")
        self.Button14.configure(activeforeground="#000000")
        self.Button14.configure(background="#d9d9d9")
        self.Button14.configure(disabledforeground="#a3a3a3")
        self.Button14.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button14.configure(foreground="#000000")
        self.Button14.configure(highlightbackground="#d9d9d9")
        self.Button14.configure(highlightcolor="black")
        self.Button14.configure(pady="0")
        self.Button14.configure(text='''x''')
        self.Button14.configure(command=lambda: unknown_support.numPressed("*"))


        self.Button15 = tk.Button(self.Frame7_24)
        self.Button15.place(relx=0.482, rely=0.256, height=44, width=57)
        self.Button15.configure(activebackground="#ececec")
        self.Button15.configure(activeforeground="#000000")
        self.Button15.configure(background="#d9d9d9")
        self.Button15.configure(disabledforeground="#a3a3a3")
        self.Button15.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button15.configure(foreground="#000000")
        self.Button15.configure(highlightbackground="#d9d9d9")
        self.Button15.configure(highlightcolor="black")
        self.Button15.configure(pady="0")
        self.Button15.configure(text='''/''')
        self.Button15.configure(command=lambda: unknown_support.numPressed("/"))


        self.Button16 = tk.Button(self.Frame7_24)
        self.Button16.place(relx=0.0, rely=0.511, height=44, width=57)
        self.Button16.configure(activebackground="#ececec")
        self.Button16.configure(activeforeground="#000000")
        self.Button16.configure(background="#d9d9d9")
        self.Button16.configure(disabledforeground="#a3a3a3")
        self.Button16.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button16.configure(foreground="#000000")
        self.Button16.configure(highlightbackground="#d9d9d9")
        self.Button16.configure(highlightcolor="black")
        self.Button16.configure(pady="0")
        self.Button16.configure(text='''%''')
        self.Button16.configure(command=lambda: unknown_support.numPressed("%"))


        self.Button17 = tk.Button(self.Frame7_24)
        self.Button17.place(relx=0.482, rely=0.511, height=44, width=57)
        self.Button17.configure(activebackground="#ececec")
        self.Button17.configure(activeforeground="#000000")
        self.Button17.configure(background="#d9d9d9")
        self.Button17.configure(disabledforeground="#a3a3a3")
        self.Button17.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button17.configure(foreground="#000000")
        self.Button17.configure(highlightbackground="#d9d9d9")
        self.Button17.configure(highlightcolor="black")
        self.Button17.configure(pady="0")
        self.Button17.configure(text='''.''')
        self.Button17.configure(command=lambda: unknown_support.numPressed("."))


        self.Button18 = tk.Button(self.Frame7_24)
        self.Button18.place(relx=0.0, rely=0.767, height=44, width=57)
        self.Button18.configure(activebackground="#ececec")
        self.Button18.configure(activeforeground="#000000")
        self.Button18.configure(background="#d9d9d9")
        self.Button18.configure(disabledforeground="#a3a3a3")
        self.Button18.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button18.configure(foreground="#000000")
        self.Button18.configure(highlightbackground="#d9d9d9")
        self.Button18.configure(highlightcolor="black")
        self.Button18.configure(pady="0")
        self.Button18.configure(text='''C''')
        self.Button18.configure(command=lambda: unknown_support.clearDisplay())


        self.Button19 = tk.Button(self.Frame7_24)
        self.Button19.place(relx=0.482, rely=0.767, height=44, width=57)
        self.Button19.configure(activebackground="#ececec")
        self.Button19.configure(activeforeground="#000000")
        self.Button19.configure(background="#d9d9d9")
        self.Button19.configure(disabledforeground="#a3a3a3")
        self.Button19.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button19.configure(foreground="#000000")
        self.Button19.configure(highlightbackground="#d9d9d9")
        self.Button19.configure(highlightcolor="black")
        self.Button19.configure(pady="0")
        self.Button19.configure(text='''=''')
        self.Button19.configure(command=lambda: unknown_support.equalPressed())


        self.Button20 = tk.Button(self.Frame7_24)
        self.Button20.place(relx=0.0, rely=0.256, height=44, width=57)
        self.Button20.configure(activebackground="#ececec")
        self.Button20.configure(activeforeground="#000000")
        self.Button20.configure(background="#d9d9d9")
        self.Button20.configure(disabledforeground="#a3a3a3")
        self.Button20.configure(font="-family {Segoe UI} -size 24 -weight bold")
        self.Button20.configure(foreground="#000000")
        self.Button20.configure(highlightbackground="#d9d9d9")
        self.Button20.configure(highlightcolor="black")
        self.Button20.configure(pady="0")
        self.Button20.configure(text='''x''')
        self.Button20.configure(command=lambda: unknown_support.numPressed("*"))

    def InsertToEntryAtCursorIndex(self, index, text):
        self.Entry1.insert(index, text)

    def GetEntryCursorIndex(self):
        return self.Entry1.index(tk.INSERT)
        # get(tk.SEL_FIRST, tk.SEL_LAST)

if __name__ == '__main__':
    vp_start_gui()
